// DataPrep Pro preview bootstrap v34: compact redesigned landing experience.
(function(){
  var VERSION='34';
  function loadCss(href,id){if(document.getElementById(id))return;var l=document.createElement('link');l.id=id;l.rel='stylesheet';l.href=href+'?v='+VERSION;document.head.appendChild(l)}
  function loadScript(src,attr){return new Promise(function(resolve){var existing=document.querySelector('script['+attr+']');if(existing){resolve();return}var s=document.createElement('script');s.src=src+'?v='+VERSION;s.async=false;s.setAttribute(attr,'1');s.onload=resolve;s.onerror=function(){console.error('DataPrep failed to load:',src);resolve()};document.head.appendChild(s)})}
  function curriculumReady(){return !!(window.topicsData&&window.topicRegistry&&document.querySelector('#topicsGrid .topic-card'))}
  function waitForCurriculum(){return new Promise(function(resolve){var n=0;(function check(){if(curriculumReady()||n++>150){resolve();return}setTimeout(check,100)})()})}
  [['global-dark-theme.css','globalDarkTheme'],['ui-polish.css','uiPolishTheme'],['lesson-contrast.css','lessonContrastTheme'],['beginner-checkpoint-engine.css','beginnerCheckpointTheme'],['learning-experience-enhancements.css','learningExperienceTheme'],['guided-practice-engine.css','guidedPracticeTheme'],['practice-system-v3.css','practiceSystemV3Theme'],['subject-tabs-v1.css','subjectTabsV1Theme'],['final-beginner-ui.css','finalBeginnerUITheme'],['intermediate-stage-flow.css','intermediateStageTheme'],['intermediate-learning-engine.css','intermediateLearningTheme'],['portfolio-enhancement.css','portfolioEnhancementTheme'],['landing-v2.css','landingV2Theme']].forEach(function(x){loadCss(x[0],x[1])});
  loadScript('etl-routing-guard.js','data-etl-routing-guard');loadScript('practice-system-v3.js','data-practice-system-v3');loadScript('subject-tabs-v1.js','data-subject-tabs-v1');loadScript('final-beginner-ui.js','data-final-beginner-ui');loadScript('beginner-navigation-fix.js','data-beginner-navigation-fix');
  loadScript('script-core.js','data-preview-core').then(waitForCurriculum).then(function(){
    document.documentElement.dataset.dataprepEnhancements='v'+VERSION;
    var queue=[['landing-v2.js','data-landing-v2'],['excel-subject-shell.js','data-excel-subject-shell'],['excel-dark-theme.js','data-excel-dark-theme'],['beginner-data-source-sync.js','data-beginner-data-source-sync'],['beginner-checkpoint-engine.js','data-beginner-checkpoint-engine'],['dedicated-subject-shell.js','data-dedicated-subject-shell'],['legacy-subject-readability.js','data-legacy-subject-readability'],['stage-focus-flow.js','data-stage-focus-flow'],['intermediate-continuity-content.js','data-intermediate-continuity-content'],['intermediate-depth-enrichment.js','data-intermediate-depth-enrichment'],['intermediate-stage-flow.js','data-intermediate-stage-flow'],['intermediate-navigation-fix.js','data-intermediate-navigation-fix'],['intermediate-continuity-shell.js','data-intermediate-continuity-shell'],['intermediate-learning-engine.js','data-intermediate-learning-engine'],['intermediate-audit-completion.js','data-intermediate-audit-completion'],['intermediate-markdown-renderer.js','data-intermediate-markdown-renderer'],['advanced-continuity-content.js','data-advanced-continuity-content'],['advanced-gap-completion.js','data-advanced-gap-completion'],['advanced-stage-flow.js','data-advanced-stage-flow'],['advanced-learning-shell.js','data-advanced-learning-shell'],['portfolio-enhancement.js','data-portfolio-enhancement'],['ui-polish.js','data-ui-polish'],['learning-experience-v2.js','data-learning-experience-v2'],['guided-practice-engine.js','data-guided-practice-engine']];return queue.reduce(function(p,item){return p.then(function(){return loadScript(item[0],item[1])})},Promise.resolve())
  }).then(function(){document.documentElement.dataset.dataprepEnhancementsReady='true';document.dispatchEvent(new CustomEvent('dataprep-enhancements-ready'))});
})();