(function(){
  function pin(){return localStorage.getItem('dataAnalyticsActivePin')||'default'}
  function subjectId(root){const t=(root.innerText||'').toLowerCase();if(t.includes('sql fundamentals'))return'sql';if(t.includes('excel & spreadsheets'))return'excel';if(t.includes('statistics essentials'))return'statistics';if(t.includes('data visualization'))return'visualization';if(t.includes('business analytics'))return'business';if(t.includes('python foundations'))return'python';if(t.includes('etl foundations'))return'etl';return'generic'}
  function cpCount(id){try{const key=id==='sql'?'dataPrepSqlCheckpoints_'+pin():id==='excel'?'dataPrepExcelCheckpoints_'+pin():'dataPrepBeginnerCp_'+id+'_'+pin();const s=JSON.parse(localStorage.getItem(key)||'{}');return Object.values(s).filter(v=>v&&v.passed).length}catch(_){return 0}}
  function moduleCount(id){if(id==='sql')return 8;if(id==='excel')return 5;const map={statistics:'statistics',visualization:'visualization',python:'python_setup'};if(map[id])return Math.ceil((window.topicsData?.[map[id]]?.lessons?.length||0)/3);if(id==='business')return Math.ceil(((window.topicsData?.business?.lessons?.length||0)+(window.topicsData?.communication?.lessons?.length||0))/3);if(id==='etl')return 4;return 0}
  function resourceHtml(id){const data={sql:['SQL clause order: SELECT → FROM → WHERE → GROUP BY → HAVING → ORDER BY','Practice joins with clear key relationships','Use EXPLAIN for performance analysis'],excel:['Formula reference and cell addressing','PivotTable workflow','Lookup and cleaning checklist'],statistics:['Descriptive statistics checklist','Probability and distribution reference','Inference interpretation guide'],visualization:['Chart-selection checklist','Dashboard design principles','Storytelling and annotation guide'],business:['KPI definition checklist','Business-case framing','Executive recommendation template'],python:['Environment setup checklist','Core Python syntax reference','Debugging and notebook workflow'],etl:['Extract/transform/load checklist','Validation and logging checklist','Pipeline reliability checklist']}[id]||['Review the lesson summaries','Use the practice questions','Complete the case study'];return `<div class="dp-fallback-tab-panel"><h3>Resources</h3><p>Quick references for this subject.</p><ul>${data.map(x=>`<li>${x}</li>`).join('')}</ul></div>`}
  function progressHtml(id){const total=moduleCount(id),passed=cpCount(id),pct=total?Math.round(passed/total*100):0;let applied=0;try{applied=localStorage.getItem('dataPrepApplied_'+pin()+'_'+id)==='1'?1:0}catch(_){}return `<div class="dp-fallback-tab-panel"><h3>Subject progress</h3><p>Learning, verified checkpoints, and applied practice are tracked separately.</p><div class="dp-fallback-progress-grid"><article><span>Modules</span><strong>${total}</strong><small>available in this subject</small></article><article><span>Verified</span><strong>${passed}/${total||0}</strong><small>${pct}% checkpoint progress</small></article><article><span>Applied practice</span><strong>${applied?'Complete':'Not yet'}</strong><small>case-study status</small></article></div></div>`}
  function activate(root,tab){const card=root.querySelector('.dp-subject-card');if(!card)return;card.dataset.activeTab=tab;root.querySelectorAll('.dp-tabs button').forEach(b=>b.classList.toggle('active',(b.textContent||'').trim().toLowerCase()===tab));card.querySelectorAll('.dp-fallback-tab-panel').forEach(x=>x.remove());if(tab==='progress')card.insertAdjacentHTML('beforeend',progressHtml(subjectId(root)));if(tab==='resources')card.insertAdjacentHTML('beforeend',resourceHtml(subjectId(root)));if(tab==='lessons')root.querySelector('[data-open-module="0"]')?.click()}
  function bind(root){const tabs=root.querySelector('.dp-tabs');if(!tabs||tabs.dataset.realTabs)return;tabs.dataset.realTabs='1';[...tabs.querySelectorAll('button')].forEach(b=>{const name=(b.textContent||'').trim().toLowerCase();if(!['overview','lessons & quizzes','progress','resources'].includes(name))return;b.addEventListener('click',e=>{if(name==='lessons & quizzes')return; e.preventDefault();e.stopImmediatePropagation();activate(root,name==='overview'?'overview':name)},true)})}
  function scan(){document.querySelectorAll('#dpSubjectShell').forEach(bind)}
  new MutationObserver(scan).observe(document.documentElement,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',scan);else scan();
})();